// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD745OsBh8Zl74QSywqzRKi6rodOrekIw',
    appId: '1:85645737322:web:6aa3edd5809444b127f913',
    messagingSenderId: '85645737322',
    projectId: 'fact-pulse',
    authDomain: 'fact-pulse.firebaseapp.com',
    storageBucket: 'fact-pulse.firebasestorage.app',
    measurementId: 'G-7ZG63S0VB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWONhuVMROQ2s49m3y96YrjAO9TKuM9MI',
    appId: '1:85645737322:android:beb4697e4ab759b227f913',
    messagingSenderId: '85645737322',
    projectId: 'fact-pulse',
    storageBucket: 'fact-pulse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVdAZPca1rRYbEBBSorC9daLHtZS-MWtA',
    appId: '1:85645737322:ios:0d14349b54699d8a27f913',
    messagingSenderId: '85645737322',
    projectId: 'fact-pulse',
    storageBucket: 'fact-pulse.firebasestorage.app',
    iosClientId: '85645737322-jh5nh682fj9hr06po5euhgeokf417t19.apps.googleusercontent.com',
    iosBundleId: 'com.example.factPulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVdAZPca1rRYbEBBSorC9daLHtZS-MWtA',
    appId: '1:85645737322:ios:0d14349b54699d8a27f913',
    messagingSenderId: '85645737322',
    projectId: 'fact-pulse',
    storageBucket: 'fact-pulse.firebasestorage.app',
    iosClientId: '85645737322-jh5nh682fj9hr06po5euhgeokf417t19.apps.googleusercontent.com',
    iosBundleId: 'com.example.factPulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD745OsBh8Zl74QSywqzRKi6rodOrekIw',
    appId: '1:85645737322:web:23d7721bd6c8c49427f913',
    messagingSenderId: '85645737322',
    projectId: 'fact-pulse',
    authDomain: 'fact-pulse.firebaseapp.com',
    storageBucket: 'fact-pulse.firebasestorage.app',
    measurementId: 'G-XKP3J1ZCKE',
  );

}